name: Deploy to AWS Elastic Beanstalk server

on:
  push:
    branches:
      - dev-2

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
        matrix: 
            node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}  # Adjust based on your project's requirements
          cache: 'npm' 

      - name: Install Dependencies and Configuration settings
        run: npm ci
    
      - name: Build Command
        run: |
          npm run build
          npm run dev

      - name: Install Configuration settings
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env

           
