name: Testing

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  integration_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"
